name: Build PokemonHnS

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    container:
      image: devkitpro/devkitpro:latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Show compiler
        run: |
          export DEVKITPRO=/opt/devkitpro
          export DEVKITARM=$DEVKITPRO/devkitARM
          export PATH=$DEVKITARM/bin:$PATH

          arm-none-eabi-gcc --version
          make --version
          python3 --version

      - name: Install Python packages
        run: |
          python3 -m pip install -r requirements.txt

      - name: Build
        run: |
          export DEVKITPRO=/opt/devkitpro
          export DEVKITARM=$DEVKITPRO/devkitARM
          export PATH=$DEVKITARM/bin:$PATH

          make modern

      - name: Upload build
        uses: actions/upload-artifact@v4
        with:
          name: build
          path: |
            *.gba
            *.elf
            *.map
            *.sym
            build/**/*.gba
            build/**/*.elf
            build/**/*.map
            build/**/*.sym
